version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ongdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src	
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - backend
    command: sh -c "npm install -D tailwindcss@latest postcss@latest autoprefixer@latest && npx tailwindcss init -p && npm start"

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: